export const STRING_GLOBAL = {
    SUBMIT: "تایید",
    ERROR: "خطا",
    SUBMIT_AND_CONTINUE: "تایید و ادامه",
    CENTIMETER: " سانتی متر ",
    KILOGRAM: "  کیلوگرم ",
    MESSAGE: "پیام",
    PLEASE_WAIT: "لطفا منتظر بمانید",
    PAYMENT: "پرداخت",
    SETTINGS: "تنظیمات",
    BACK: "بازگشت",
    MY_TICKET: "بلیت های من",
    SEARCH: "جستجو",
    NOT_FOUND: "موردی یافت نشد",
    NO_CONFIG: "ورودی های این ویجت صحیح نمی باشد",
    SEE_ALL: "مشاهده همه",
    DIRECTOR: "کارگردان",
    ABOUT: "درباره",
    SELECT_SANS_AND_CINEMA: "انتخاب سانس و سینما",
    SELECT_PROVINCE: "انتخاب  استان ",
    SELECT_CITY: "انتخاب  شهر ",
};
