export const STRING_GLOBAL = {
    SUBMIT: "تایید",
    ERROR: "خطا",
    SUBMIT_AND_CONTINUE: "تایید و ادامه",
    CENTIMETER: " سانتی متر ",
    KILOGRAM: "  کیلوگرم ",
    MESSAGE: "پیام",
    PLEASE_WAIT: "لطفا منتظر بمانید",
    PAYMENT: "پرداخت",
    SETTINGS: "تنظیمات",
    BACK: "بازگشت",
    MY_TICKET: "بلیت های من",
    SEARCH: "جستجو",
    NOT_FOUND: "موردی یافت نشد",
};
